### PR TITLE
Database refactor

### PR DESCRIPTION
**Pull request by MarchandMD**
Hey Timothy,

I'm interested in Thinkful bootcamp, but have some questions I'd like to ask of it's former students.

Would you be willing to answer some of my questions, or chat about your experience?

I know this is a little random, but I couldn't find your email address online, and figured you might check out Github occassionally. Anyway, let me know. 

Thanks for reading.

### CODE REVIEW

**Comment by tsputzke** [comment]
Hey Michael,

Sure, I'd be happy to help- let me know what questions you have. I am still
2 months (hopefully) from graduating the full stack flex program (~6 month
program), so I can't offer anything about the job search. I'm sure you have
checked out the CIRR outcome stuff for that anyway.

Best,
Tim

**Comment by MarchandMD** [comment]
Thanks for responding Tim.

Yeah, I looked at the CIRR and am doing other research, but I want to do my
due diligence before making any major decisions.

What were you capable before you started? Could you build a basic website?
Did you know what an IDE was? Did the command line intimidate you?

Which payment method did you opt for?

Are you interested in finding work BEFORE you graduate? After so many
months, do you feel comfortable applying for a position today, before
completing?

Boy, that's a lot of questions, so I'll let you answer what you want to. No
rush.

Thanks again Tim.

And please, feel free to click around my portfolio... I'd love your first
impressions. No need to spend a lot of time there....

https://marchandmd.github.io/
Michael Marchand

**Comment by tsputzke** [comment]
Michael,

Are you learning via the Odin Project, or Free Code Camp or something? Your
portfolio looks good so far, you obviously already have a strong foundation
in the basics that you have included things like media queries in your CSS,
and a working knowledge of JS.

*What were you capable before you started? *

*Could you build a basic website?*
*Did you know what an IDE was? Did the command line intimidate you?*

I had ~8 months of Free Code Camp and youtube videos prior to Thinkful and
had attended a couple of 'build a website in an afternoon' type local
meetups for HTML and CSS. Very basic working knowledge. I had also taken a
(paid) 5-week 'javascript fundamentals' course offered by a local bootcamp
for my JS. Oh, I also was halfway through Colt Steele's udemy course on
web-dev. I could build a basic website, nothing fancy (less than you seem
capable of now). I did know what an IDE was from my prep, but had only used
the command line a couple of times in a code-along or two.

*Which payment method did you opt for?*

I started month to month, but they let me change to the lump sum after a
few weeks when I decided that I was 100% committed (financed through Skills
Fund). The Thinkful finance people were extremely helpful and knowledgable.



*Are you interested in finding work BEFORE you graduate? After so
manymonths, do you feel comfortable applying for a position today,
beforecompleting?*

I feel comfortable applying to entry-level front-end positions today,
skills-wise, but I have been way too busy to have set up a good portfolio
website and to polish my projects. I have honestly thought of dropping out
early to do this...I'm now working in Node and not loving the server-side
stuff. Part of the curriculum has you start preparing (first your resume,
linked-in, etc. and ultimately later portfolio and applying to jobs) well
in advance of graduation.

For what it's worth, here's some context: I am in the Research Triangle, NC
(Raleigh), 31 years old with a B.S. in Plant Sciences and 10 years in
plant-related fields. I was going to be attending a local boot camp (even
lost some money on a down payment) but opted for a flexible online program
last minute (I am the sole provider with a wife and two children). I chose
Thinkful because: 1) flexibility. 2) job guarantee (read the fine print to
make sure you qualify) 3) I liked the mentorship aspect (twice a week
meetings with a senior dev).

I don't regret my decision at all. I could've learned this all on my own,
honestly, but it would've taken twice as long and I would've been insanely
frustrated along the way. Now that I'm over halfway through the program,
the only downsides are that the graduation plan (timetable) is sort of
insane to actually graduate in 6 months (I think CIRR showed the average
was 225 days or something) and the curriculum at times will be confusing
and need a fair amount of supplementation from outside resources. I put in
25-30 hours a week, and I'm still ~2 weeks behind schedule for a 6-month
graduation. It's exhausting and stressful, and grueling, but I plan to be
part of the 40% who graduates and then in the 80+% of those who find a dev
job within 6 months.

I hope this helps, best of luck!
Tim

**Comment by MarchandMD** [comment]
Thanks Tim!

I've been learning through The Odin Project for over a year now; Though
most of my progress was within the last 3 months.

I started doing FreeCodeCamp stuff a couple of months ago, just to branch
out a little bit, and try something different. Now though I'm a little
overwhelmed, and am taking some time off because I realize I'm an advanced
beginner. Getting beyond this stage to become "intermediate" is a huge
step, and I've been practicing some more fundamentals. Like building
websites, practicing with the Rails framework, etc.

Thanks for looking at my portfolio. It sounds like you're at a similar sort
of place as I am... I've learned a lot about Object-Orientation which is
server-side stuff... but I don't really have the technical "know-how" to
apply OOP into a program or app. And building with OOP is closely tied to
testing and writing tests... and that's a completely separate language to
learn on top of HTML, CSS, JS, Ruby and Rails. So it's even more
frustrating because I "get" the concepts, but there's few resources for me
to follow to practice working with Objects separate from writing tests.
It's really strange....

As far as the media queries go: Recently it just sort of made sense. Maybe
I learned that I have the "chops" to be able to build a full desktop app...
and was finally able to make the connection to the idea of designing
"mobile-first". And it was actually a lot easier when things finally
clicked.

But here's also where I am: I can build a website, but I don't really have
content. Like, it's super tough to think up content for an entire website.
And I end up being critical of my own designs. Like, I wish there was
someone else who was capable of looking at a simple website, and willing to
help me make design choices, or at least talk about stuff, and make design
decisions at the same time as me. Even something as silly as a portfolio. I
know it sounds simple, but just having someone else watching while I do the
layout and styling I feel would be helpful.

Getting the portfolio ready seems to be tough. Like, there's so many people
out there that are super capable; It seems like networking is almost as
important, if not more important, than proving what you can do with a
language.

Good to know you were able to make a change to the payment arrangement.

I'll take a closer look at the fine print.

And thanks for providing the context; I'm a single guy, no kids, 40 yo. If
you looked at my resume you saw my education and professional life is a far
cry from web development. I just want to make a good decision; it's really
good to hear your side of things.

If there's anything I can do to help you build your web presence, please
let me know. I think it'd be good practice and I love sharing knowledge.

Thanks again! I'll most likely re-read your email and have some more
questions later.

Enjoy the weekend!

Sincerely,

Michael Marchand

**Pull request closed without merging**
